name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            toxenv: "py37"
          - python-version: "3.8"
            toxenv: "py38"
          - python-version: "3.9"
            toxenv: "py39"
          - python-version: "pypy3"
            toxenv: "pypy3"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Building project
        env:
          TOXENV: ${{ matrix.toxenv }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          pip install -r requirements-dev.txt
          tox -e ${TOXENV}
          coveralls --service=github